# Generated by Django 5.0.3 on 2024-03-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('status', models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], max_length=15, verbose_name='опубликовать')),
                ('homepage_status', models.BooleanField(default=False, verbose_name='на главной странице')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
    ]
