# Generated by Django 5.0.3 on 2024-03-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='опубликовать'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(default=False, verbose_name='опубликовать'),
        ),
    ]
