# Generated by Django 5.0.3 on 2024-04-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotel_slug_alter_room_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelmedia',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/hotels/'),
        ),
        migrations.AlterField(
            model_name='roommedia',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/rooms/'),
        ),
    ]
