# Generated by Django 5.0.3 on 2024-04-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotelmedia_image_alter_roommedia_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo_hotel',
            field=models.ImageField(blank=True, upload_to='photos/hotels/logo/'),
        ),
    ]
