# Generated by Django 5.0.3 on 2024-04-01 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_room_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_booked',
        ),
    ]
