# Generated by Django 5.0.3 on 2024-04-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_hotel_recomended_alter_hotel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='short_desc',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='recomended',
            field=models.BooleanField(default=False, verbose_name='рекомендовать'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.BooleanField(default=False, verbose_name='опубликовать'),
        ),
    ]
