# Generated by Django 5.0.3 on 2024-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_room_short_desc_alter_hotel_recomended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='logo_hotel',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/hotels/logo/', verbose_name='главное фото'),
        ),
    ]
