# Generated by Django 5.0.3 on 2024-04-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_hotel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_guest',
            field=models.IntegerField(default=3, verbose_name='максимум гостей в номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='parking',
            field=models.BooleanField(default=False, verbose_name='парковочное место'),
        ),
        migrations.AddField(
            model_name='room',
            name='wifi',
            field=models.BooleanField(default=False, verbose_name='бесплатный WIFI'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1-м', 'одноместный номер'), ('2-м 1-к', 'двухместный номер 1 кровать'), ('2-м 2-к', 'двухместный номер 2 кровати'), ('Люкс 2-м', 'Двухместный люкс'), ('3-м', 'Трёхместный')], max_length=15, verbose_name='тип номера'),
        ),
    ]
