# Generated by Django 5.0.3 on 2024-04-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_room_max_guest_room_parking_room_wifi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='baths',
            field=models.IntegerField(default=False, verbose_name='санузлов'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='short_desc',
            field=models.TextField(blank=True, max_length=100, verbose_name='краткое описание'),
        ),
    ]
