# Generated by Django 5.0.3 on 2024-04-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_room_bads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='short_desc',
            field=models.TextField(blank=True, max_length=250, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='short_desc',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
