# Generated by Django 5.0.3 on 2024-04-07 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='location_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotels.city', verbose_name='город'),
        ),
    ]
