# Generated by Django 5.0.3 on 2024-04-07 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_alter_hotel_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.city', verbose_name='город'),
        ),
    ]
