# Generated by Django 5.0.3 on 2024-04-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_alter_city_title_alter_hotel_location_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='когда бронировали'),
        ),
    ]
