# Generated by Django 5.0.3 on 2024-04-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
