# Generated by Django 5.0.3 on 2024-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0028_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True, verbose_name='опубликовать'),
        ),
    ]
